export const SETTINGS = {
  // APP SETTINGS
  REACT_APP_SUBGRAPH: process.env.VITE_REACT_APP_SUBGRAPH as string,
  REACT_APP_EON: process.env.VITE_REACT_APP_EON as string,
  REACT_APP_GALAXYGAME: process.env.VITE_REACT_APP_GALAXYGAME as string,
  REACT_APP_CHAIN: process.env.VITE_REACT_APP_CHAIN as string,
  REACT_APP_PYTHEAS: process.env.VITE_REACT_APP_PYTHEAS as string,
  INFURA_ID: process.env.VITE_INFURA_ID as string,
  // CONTRACT ADDRESSES
  SHATTEREDWLADDRESS: process.env.VITE_SHATTEREDWLADDRESS as string,
  SHATTEREDEONADDRESS: process.env.VITE_SHATTEREDEONADDRESS as string,
  PIRATEGAMESADDRESS: process.env.VITE_PIRATEGAMESADDRESS as string,
  COLONISTADDRESS: process.env.VITE_COLONISTADDRESS as string,
  PIRATESADDRESS: process.env.VITE_PIRATESADDRESS as string,
  ORBITALBLOCKADEADDRESS: process.env.VITE_ORBITALBLOCKADEADDRESS as string,
  PYTHEASADDRESS: process.env.VITE_PYTHEASADDRESS as string,
  RAWADDRESS: process.env.VITE_RAWADDRESS as string,
  EONADDRESS: process.env.VITE_EONADDRESS as string,
  DENOFALGOLADDRESS: process.env.VITE_DENOFALGOLADDRESS as string,
  REFINERYADDRESS: process.env.VITE_REFINERYADDRESS as string,
  // CONSTANTS
  MAX_COLONISTS: 60000,
  ETH_PRE_PUBLIC_SALE_PRICE: parseFloat(process.env.VITE_ETH_PRE_PUBLIC_SALE_PRICE as string),
  ETH_PUBLIC_SALE_PRICE: parseFloat(process.env.VITE_ETH_PUBLIC_SALE_PRICE as string),
};
